name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install lcov
      run: sudo apt-get install -y lcov
    
    - name: Tests
      run: |
        ./tests/tests.cpp

    - name: Coveralls
      uses: coverallsapp/github-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/coverage.info
