name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install lcov
      run: sudo apt-get install -y lcov

    - name: Run tests
      run: |
        ./tests/tests.cpp
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --remove coverage.info '${{github.workspace}}/third-party/gtest/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Coveralls
      uses: coverallsapp/github-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/coverage.info
